language: c

matrix:
  include:
    - os: linux
      compiler: gcc
      env: BUILD=linux_gcc
    - os: linux
      compiler: clang
      addons:
          apt:
            packages:
            - libncurses5-dev
      env: BUILD=linux_clang
    - os: osx
      osx_image: xcode9.3beta
      env: BUILD=osx_xcode9_3
    - os: osx
      osx_image: xcode9.2
      env: BUILD=osx_xcode9_2

script:
  - ./configure --prefix=$PWD/temp-build
  - make
  - make install
  - cd test
  - ./basic.sh
  - rm -rf tmp-home
  - ./purging.sh
  - cd ..
  - make uninstall

notifications:
  slack: removetowaste:u16fiNsaMeLmg7J4WXifW3Zm
